version: '3.1'

services:
  redis:
    image: redis:3.2.10
    restart: on-failure
    command: redis-server --requirepass OveoGsEw1345QsdS1488DzVC
    ports:
      - 6379:6379

  mongo:
    image: mongo:4.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
      - AUTH_DB=admin
      - DB_USER=bizzan
      - DB_PASS=fdafdsafdsa
      - DB_NAME=bitrade
    ports:
      - 27017:27017
    volumes:
      - ./db-entrypoint/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:1.17.3-alpine
    restart: on-failure
    volumes:
      - ./nginx/:/etc/nginx/
    ports:
      - 8801:8801

  mongo-express:
    image: mongo-express:0.45.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_SITE_COOKIESECRET: liquidity-generator-cookies-secret
      ME_CONFIG_SITE_SESSIONSECRET: liquidity-generator-session-secret
      ME_CONFIG_BASICAUTH_USERNAME: liquidity-generator-user
      ME_CONFIG_BASICAUTH_PASSWORD: sdf2L%^VsL@d810we200034_Jys&9w9g9sDGsz*A*q*1*2*1238
      ME_CONFIG_OPTIONS_EDITORTHEME: monokai
    depends_on:
      - mongo
    restart: on-failure

#
#  mysql:
##    image: mysql:5.5.58
#    image: mysql:5.7.4
#    environment:
##      MYSQL_HOST: 'localhost'
#      MYSQL_DATABASE: 'bizzan'
##      MYSQL_USER: 'bizzan'
##      MYSQL_PASSWORD: 'bizzan'
##      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#      MYSQL_ROOT_PASSWORD: 'bizzan'
#    ports:
#      - 3306:3306
#
#  adminer:
#    image: adminer:latest
#    ports:
#      - 8082:8080
#    depends_on:
#      - mysql

  zookeeper:
    image: zookeeper:3.5.5

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-web-view:
    image: sourcelaborg/kafka-webview:latest
    ports:
      - 8053:8080
    depends_on:
      - kafka
